basePath: /api/v1
consumes:
  - application/json
info:
  license:
    name: ISC
  title: Ecommerce Api docs
  version: 0.1.0
paths:
  /products:
    get:
      operationId: getAllProducts
      produces:
        - application/json
      responses:
        "200":
          description: Response Status OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Product"
      description: "Get the list of products in the store"
produces:
  - application/json
swagger: "2.0"
securityDefinitions: {}
host: localhost:5050

definitions:
  Product:
    type: object
    properties:
      id:
        description: Id of the product
        type: integer
      title:
        description: The name of the product
        type: string
      description:
        description: The description of the product
        type: string
      imagePath:
        description: Link to represent the image of the product
        type: string
      category:
        description: The category of the product
        type: string
      price:
        description: The price of the product
        type: number
      amount:
        description: The remaining amount of the product
        type: interger
